# Generated by Django 3.0.5 on 2023-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=40)),
                ('sale', models.CharField(max_length=10)),
                ('qry', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('U', 'U')], max_length=1, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
